name: CI
on:
  push:
  pull_request:

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: pypa/hatch@install
      - run: hatch run types:check
  fmt:
    name: Format and lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: pypa/hatch@install
      - run: hatch fmt --check
